package com.example.purpleapp.api

object URLs {

 private val ROOT_URL = "https://affetta.com/affetta_api/registrationapi.php?apicall="
private val ROOT_OTP_URL = "https://affetta.com/affetta_api/otp_verification.php?apicall="

//     private  val ROOT_URL = "http://192.168.0.106/affetta_api/registrationapi.php?apicall="
//    private val ROOT_OTP_URL = "http://192.168.0.106/affetta_api/otp_verification.php?apicall="



        val URL_REGISTER = ROOT_URL + "signup"
        val URL_LOGIN = ROOT_URL + "login"
        val URL_GET_BANNER = ROOT_URL + "bannerAds"
        val URL_GET_CATEGORIES = ROOT_URL + "categories"
        val URL_GET_AFTER_CATEGORIES = ROOT_URL + "afterCategories"
        val URL_GET_SUB_CATEGORIES = ROOT_URL + "subCategories"
        val URL_GET_CHILD_CATEGORIES = ROOT_URL + "childCategories"
        val URL_GET_SPECIAL_PRODUCTS = ROOT_URL + "specialProducts"
        val URL_GET_SPECIAL_PRODUCTS_ALL = ROOT_URL + "specialProductsAll"
        val URL_GET_POPULAR_PRODUCTS = ROOT_URL + "popularProducts"
        val URL_GET_POPULAR_PRODUCTS_ALL = ROOT_URL + "popularProductsAll"
        val URL_GET_OFFER_BANNER = ROOT_URL + "offerBanners"
        val URL_GET_BRANDS = ROOT_URL + "brands"
        val URL_GET_BRAND_NAMES_ALL = ROOT_URL + "brandNamesAll"
        val URL_GET_COMBO_OFFERS = ROOT_URL + "comboOffers"
        val URL_GET_STOCK_CLEARANCE = ROOT_URL + "stockClearance"
        val URL_GET_STOCK_CLEARANCE_ALL = ROOT_URL + "stockClearanceAll"
        val URL_GET_COMBO_OFFERS_ALL = ROOT_URL + "comboOffersAll"
        val URL_GET_NEW_ARRIVALS = ROOT_URL + "newArrivals"
        val URL_GET_NEW_ARRIVALS_ALL = ROOT_URL + "newArrivalsAll"
        val URL_GET_HOT_DEALS = ROOT_URL + "deals"
        val URL_GET_HOT_DEALS_ALL = ROOT_URL + "dealsAll"
        val URL_GET_PARTICULAR_CATEGORY_PRODUCTS = ROOT_URL + "getParticularSubCategoryProducts"
        val URL_GET_PARTICULAR_CHILD_CATEGORY_PRODUCTS = ROOT_URL + "getParticularChildCategoryProducts"
        val URL_GET_SIMILAR_PRODUCTS = ROOT_URL + "getSimilarProducts"
        val URL_GET_PARTICULAR_BRAND_PRODUCTS = ROOT_URL + "getParticularBrandProducts"
        val URL_ADD_TO_CART = ROOT_URL + "addToCart"
        val URL_GET_MY_CART = ROOT_URL + "getMyCart"
        val URL_GET_MY_SHIPMENT_DATA = ROOT_URL + "getMyShipmentData"
       // val URL_GET_MY_CURRENT_SHIPMENT_DATA = ROOT_URL + "getMyCurrentShipmentData"
        val URL_GET_MY_WISH_LIST = ROOT_URL + "getMyWishlist"
        val URL_GET_PRODUCT_DETAILED_DESCRIPTION = ROOT_URL + "getProductDetailDescription"
        val URL_ADD_TO_WISH_LIST = ROOT_URL + "addToWishList"
        val URL_EDIT_PROFILE = ROOT_URL + "editMyProfile"
        val URL_EDIT_ADDRESS = ROOT_URL + "editMyAddress"
        val URL_DELETE_FROM_MY_WISH_LIST = ROOT_URL + "deleteFromMyWishList"
        val URL_DELETE_FROM_MY_CART = ROOT_URL + "deleteFromMyCart"
        val URL_ADD_TO_CART_FROM_WISHLIST = ROOT_URL + "addToCartFromWishlist"
        val URL_UPDATE_MY_CART_QUANTITY = ROOT_URL + "updateMyCartQuantity"
        val URL_GET_CATEGORY_NAMES_ALL = ROOT_URL + "getCategoryNamesAll"
        val URL_GET_HOME_SEARCHED_PRODUCTS = ROOT_URL + "getHomeSearchedProducts"
        val URL_DELETE_ALL_MY_CART = ROOT_URL + "deleteAllMyCart"
        val URL_DELETE_ALL_FROM_MY_WISH_LIST = ROOT_URL + "deleteAllFromMyWishList"
        val URL_GET_MY_CART_TOTAL_PRICE = ROOT_URL + "getMyCartTotalPrice"
        val URL_GET_MY_ORDERS = ROOT_URL + "getMyOrders"
        val URL_GET_CART_ITEMS_COUNT = ROOT_URL + "cartItemsCount"
        val URL_CONFIRM_ORDER = ROOT_URL + "confirmOrder"
        val URL_INSERT_BILL_DETAILS = ROOT_URL + "insertBillDetails"
        val URL_UPDATE_PROFILE_PICTURE = ROOT_URL + "updateProfilePicture"
        val URL_GET_PROFILE_PICTURE = ROOT_URL + "getProfilepicture"
        val URL_GET_MY_CURRENT_ORDER = ROOT_URL + "getCurrentOrder"
        val URL_ABOUT_APP = ROOT_URL + "aboutApp"
        val URL_GET_MY_ADDRESS = ROOT_URL + "getMyAddress"
       val URL_CUSTOMER_SUPPORT = ROOT_URL + "customerSupport"
       val URL_GET_COLORS = ROOT_URL + "getColors"
       val URL_GET_SIZES = ROOT_URL + "getSizes"
       val URL_GET_SELECTED_SIZE_DATA = ROOT_URL + "getDataForSelectedSize"
       val URL_GET_CHILD_CATEGORY_COUNT = ROOT_URL + "childCategoryCount"


      // Otp verification Url's
        val URL_SEND_OTP = ROOT_OTP_URL + "sendotp"
        val URL_VERIFY_OTP = ROOT_OTP_URL + "verifyotp"

}

